version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/roed_to_aid_be
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          PGHOST: localhost
          PGUSER: roed_to_aid_be
          RAILS_ENV: test
      - image: postgres:13.2
        environment:
          POSTGRES_USER: roed_to_aid_be
          POSTGRES_DB: roed_to_aid_be_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: roes_to_aid_be
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:migrate
      - run: bundle exec rspec
